"""Stage 2: PSE-based SC-Para extraction.

Sends ALM-generated captions to an LLM-based Paralinguistic State Extractor
(PSE, e.g. DeepSeek-R1-Distill-Qwen) served by vLLM, mapping each caption into
a structured SC-Para vector (prosody states + depression-related paralinguistic
evidence score). Supports processing only a subset of subjects/utterances
instead of the full dataset.
"""

import os
import re
import json
import time
import random
import threading
import concurrent.futures
from pathlib import Path
from typing import Optional, Any

from openai import OpenAI

# ========== Configuration ==========
BATCH_JSON = os.getenv("BATCH_JSON", "rest_captions.jsonl")
OUTPUT_DIR = os.getenv("OUTPUT_DIR", "caption_analysis_results")
USE_STREAM = False  # non-streaming is recommended for batch processing
DELAY_SECONDS = float(os.getenv("DELAY_SECONDS", "0.2"))  # only applied in 'sequential' mode
# Processing mode: 'sequential' (one request at a time) | 'concurrent' (higher throughput)
MODE = os.getenv("MODE", "sequential")
MAX_WORKERS = int(os.getenv("MAX_WORKERS", "5"))  # concurrency level, only used in 'concurrent' mode

# ===== Sampling configuration (for testing/development on a subset instead of the full dataset) =====
# 'subjects':   randomly sample N subjects and run all of their utterances
# 'utterances': randomly sample N utterances
# empty/None:   run the full dataset
SAMPLE_MODE = os.getenv("SAMPLE_MODE", "subjects") or None
SAMPLE_N = int(os.getenv("SAMPLE_N", "5"))
SAMPLE_SEED = int(os.getenv("SAMPLE_SEED", "42"))  # fixed seed for reproducibility


def get_subject_id(item: dict) -> str:
    """Resolve the subject ID: prefer the `subject_id` field in the JSONL
    record, otherwise infer it from the leading digits of the wav_path
    filename."""
    sid = item.get("subject_id")
    if sid is not None and str(sid).strip():
        return str(sid)
    wav = item.get("wav_path") or item.get("utterance_id") or ""
    m = re.match(r"(\d+)", Path(str(wav)).stem)
    return m.group(1) if m else "unknown"


def load_records(path: str) -> list:
    """Load records, supporting two input formats:
    1) JSONL: one JSON object per line
       (fields: caption / wav_path / utterance_id / subject_id)
    2) Captioner batch output: a single JSON object with a "results" array
       (fields: output_text / audio_file)
    """
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read().strip()
    if not text:
        return []
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            data = data.get("results", [])
        return data if isinstance(data, list) else []
    except json.JSONDecodeError:
        # Whole-file parse failed -> fall back to line-by-line JSONL parsing
        return [json.loads(line) for line in text.splitlines() if line.strip()]


def normalize_item(item: dict, idx: int) -> dict:
    """Normalize field names from captioner output (audio_file/output_text)
    to the fields expected by this script (wav_path/caption)."""
    wav = item.get("wav_path") or item.get("audio_file") or ""
    stem = Path(item.get("audio_name") or wav).stem if (item.get("audio_name") or wav) else ""
    return {
        "caption": item.get("caption") or item.get("output_text") or "",
        "wav_path": wav,
        "utterance_id": item.get("utterance_id") or stem or f"idx{idx+1}",
        "subject_id": item.get("subject_id"),
        "timestamp": item.get("timestamp"),
        "status": item.get("status", "success"),
    }

# ====== vLLM server configuration ======
VLLM_BASE_URL = os.getenv("VLLM_BASE_URL", "http://127.0.0.1:8000/v1")
VLLM_MODEL = os.getenv("VLLM_MODEL", "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B")

# vLLM usually doesn't validate the API key, but the OpenAI SDK requires this field to be set
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY", "EMPTY"), base_url=VLLM_BASE_URL)

SYSTEM_PROMPT = """You are an expert in paralinguistic analysis of depression-related speech patterns.

IMPORTANT CONSTRAINTS:
- You CANNOT infer identity, mental diagnosis, or life situation.
- You are NOT making a medical diagnosis.
- Your task is to estimate the strength of DEPRESSION-RELATED ACOUSTIC CUES at the utterance level ONLY.

Input:
A caption generated by an audio-language model for a single utterance.
The caption may contain:
- acoustic or vocal descriptions
- semantic or contextual inference

Your task:
1. Extract acoustically observable vocal and paralinguistic information.
2. Based on acoustic cues, estimate the presence and strength of depression-related speech characteristics.
3. If acoustic information is sparse or ambiguous, use "unknown" and reduce confidence.

Depression-related acoustic cues may include (but are not limited to):
- reduced pitch variability or flattened intonation
- monotonous or restricted prosodic range
- slow or irregular speaking rate
- increased pauses or hesitation
- reduced vocal energy or intensity
- breathy, tense, or hoarse voice quality
- unstable or reduced articulatory clarity

Output STRICTLY in the following JSON format.
Each JSON corresponds to ONE utterance.

{
  "prosody": {
    "pitch_variability": "flat/moderate/high/unknown",
    "speaking_rate": "slow/medium/fast/unknown",
    "rhythm": "steady/irregular/unknown",
    "pauses": "few/moderate/many/unknown",
    "energy": "low/medium/high/unknown"
  },
  "voice_quality": {
    "breathiness": "none/mild/strong/unknown",
    "tension": "none/mild/strong/unknown",
    "hoarseness": "none/mild/strong/unknown",
    "clarity": "clear/muffled/unstable/unknown"
  },
  "depression_acoustic_score": {
    "value": 0-100,
    "confidence": 0.0-1.0
  },
  "justification": "Brief explanation based ONLY on acoustic and vocal evidence."
}

If information is insufficient, use 'unknown' and lower confidence.

IMPORTANT: Output ONLY valid JSON. No extra text outside JSON.
"""

def _safe_get_reasoning(msg: Any) -> str:
    """Return reasoning_content if present; not all backends expose this field."""
    return getattr(msg, "reasoning_content", "") or ""


def analyze_caption(caption: str, use_stream: bool = False) -> Optional[dict]:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT + "\nReturn ONLY valid JSON. No code fences. No explanations."},
        {"role": "user", "content": f"Caption:\n{caption}"}
    ]
    try:
        if use_stream:
            response = client.chat.completions.create(
                model=VLLM_MODEL,
                messages=messages,
                stream=True,
                temperature=0,
                top_p=1.0,
                response_format={"type": "json_object"}  # force JSON output
            )
            content = ""
            for chunk in response:
                delta = chunk.choices[0].delta
                if delta.content:
                    content += delta.content
        else:
            response = client.chat.completions.create(
                model=VLLM_MODEL,
                messages=messages,
                stream=False,
                temperature=0,
                top_p=1.0,
                response_format={"type": "json_object"}  # force JSON output
            )
            content = response.choices[0].message.content or ""

        try:
            return {"analysis": json.loads(content)}
        except json.JSONDecodeError:
            # Fallback: extract the last brace-enclosed block
            m = re.search(r'\{.*\}', content, re.S)
            if m:
                return {"analysis": json.loads(m.group(0)), "note": "parsed by fallback"}
            return {"raw_content": content, "error": "JSON parse failed"}
    except Exception as e:
        return {"error": str(e), "caption": caption}

def main():
    print(f"vLLM base_url: {VLLM_BASE_URL}")
    print(f"vLLM model:    {VLLM_MODEL}")
    print(f"Reading file: {os.path.abspath(BATCH_JSON)}")

    raw_records = load_records(BATCH_JSON)
    results_list = [normalize_item(it, i) for i, it in enumerate(raw_records)]

    n_bad = sum(1 for it in results_list if it["status"] != "success")
    if n_bad:
        print(f"[Warning] {n_bad} records have status != success, excluding them")
        results_list = [it for it in results_list if it["status"] == "success"]

    print(f"Found {len(results_list)} records")

    if not results_list:
        print("File is empty or failed to parse")
        return

    print(f"\nFields of first record: {list(results_list[0].keys())}")
    print(f"First record sample: {json.dumps(results_list[0], indent=2, ensure_ascii=False)[:200]}")

    # ===== Sampling (process only a subset instead of the full dataset) =====
    population_total = len(results_list)
    pop_subjects = sorted({get_subject_id(it) for it in results_list})
    population_subjects = len(pop_subjects)

    if SAMPLE_MODE and SAMPLE_N:
        rnd = random.Random(SAMPLE_SEED)
        if SAMPLE_MODE == "subjects":
            chosen = set(rnd.sample(pop_subjects, min(SAMPLE_N, population_subjects)))
            results_list = [it for it in results_list if get_subject_id(it) in chosen]
            print(f"Sampled {len(chosen)}/{population_subjects} subjects "
                  f"({len(results_list)}/{population_total} utterances, seed={SAMPLE_SEED})")
            if len(chosen) <= 1 < population_total:
                print("[Warning] Only 1 subject was identified. Check the subject_id field "
                      "or wav_path naming in the JSONL, otherwise sampling is equivalent to a full run")
        elif SAMPLE_MODE == "utterances":
            results_list = rnd.sample(results_list, min(SAMPLE_N, population_total))
            print(f"Sampled {len(results_list)}/{population_total} utterances (seed={SAMPLE_SEED})")
        else:
            print(f"Error: unsupported sample mode '{SAMPLE_MODE}', use 'subjects' or 'utterances'")
            return

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    abs_output = os.path.abspath(OUTPUT_DIR)
    print(f"\nOutput directory: {abs_output}\n")

    total = len(results_list)
    success_count = 0
    fail_count = 0

    # Pre-filter: invalid captions / already-processed results (resume support)
    todo = []
    for idx, item in enumerate(results_list):
        caption = item.get("caption") or ""
        utterance_id = item.get("utterance_id", f"idx{idx+1}")

        if not caption or not isinstance(caption, str):
            print(f"[{idx+1}/{total}] Skipped: no valid caption (available fields: {list(item.keys())})")
            fail_count += 1
            continue

        output_path = os.path.join(OUTPUT_DIR, f"analysis_{utterance_id}.json")
        if os.path.exists(output_path):
            print(f"[{idx+1}/{total}] Skipped: analysis_{utterance_id}.json already exists")
            success_count += 1
            continue

        todo.append((idx, item, output_path))

    n_todo = len(todo)
    print(f"\n{n_todo} items to process, mode: {MODE}"
          + (f" (workers={MAX_WORKERS})" if MODE == "concurrent" else ""))

    lock = threading.Lock()
    counters = {"success": success_count, "fail": fail_count, "done": 0}

    def process_one(task):
        idx, item, output_path = task
        caption = item["caption"]
        audio_file = item.get("wav_path", "")
        utterance_id = item.get("utterance_id", f"idx{idx+1}")
        subject_id = get_subject_id(item)

        result = analyze_caption(caption, use_stream=USE_STREAM)

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump({
                    "index": idx + 1,
                    "utterance_id": utterance_id,
                    "wav_path": audio_file,
                    "subject_id": subject_id,
                    "timestamp": item.get("timestamp"),
                    "caption": caption,
                    "analysis_result": result
                }, f, indent=2, ensure_ascii=False)
        except Exception as e:
            with lock:
                counters["fail"] += 1
                counters["done"] += 1
            print(f"[{counters['done']}/{n_todo}] {utterance_id} failed to save: {e}")
            return

        ok = result and "error" not in result
        with lock:
            counters["done"] += 1
            done = counters["done"]
            if ok:
                counters["success"] += 1
            else:
                counters["fail"] += 1
        status = "OK" if ok else "FAIL"
        msg = f"[{status}] [{done}/{n_todo}] {utterance_id}"
        if not ok:
            msg += f" error: {(result or {}).get('error')}"
        print(msg)

    if MODE == "concurrent":
        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            list(executor.map(process_one, todo))
    else:
        for i, task in enumerate(todo):
            process_one(task)
            if DELAY_SECONDS and i < n_todo - 1:
                time.sleep(DELAY_SECONDS)

    success_count = counters["success"]
    fail_count = counters["fail"]

    print(f"\nDone. Success: {success_count}, Failed: {fail_count}")
    print(f"Results saved to: {abs_output}")

if __name__ == "__main__":
    main()
